# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a currupted csv file!

## Objectives
You will be able to:
* Import data from csv files and Excel files
* Understand and explain key arguments for imports
* Save information to csv and Excel files
* Access data within a Pandas DataFrame (print() and .head())

In [14]:
#Loading Files with Summary or Meta Data

#Load either of the files Zipcode_Demos.csv or Zipcode_Demos.xlsx. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

#All data files are stored in a folder titled 'Data'.

In [15]:
#Your code here
import pandas as pd
zipcsv = pd.read_csv('Data/Zipcode_Demos.csv', header=47)
#zipcsv.head()
zipcsv.tail()

#Data shows up as 'Not a Number' so we need to read the tail of the CSV/Excel File.

#zipxlsx = pd.read_excel('Data/Zipcode_Demos.xlsx')
#zipxlsx.head()

,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
5,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0.0,6,1.0,0,0,6,100
6,54,10007,1,0,0.00,1,1.00,0,0,1,...,1,100,1,1.0,0,0.0,0,0,1,100
7,55,10009,2,0,0.00,2,1.00,0,0,2,...,2,100,0,0.0,2,1.0,0,0,2,100
8,56,10010,0,0,0.00,0,0.00,0,0,0,...,0,0,0,0.0,0,0.0,0,0,0,0
9,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0.0,3,1.0,0,0,3,100

## Level Up (Optional)

### Loading Corrupt CSV files

Occassionally, you encountered some really ill formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is suppossed to use quotes to differentiate between the commas denoting fields and commas within those fields themselves. For example, we could have a table like this:  

ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restuarant was pretty good, we had a great time.,98765

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restuarant was pretty good, we had a great time.","98765"

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled Yelp_Reviews_corrupt.csv. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [ ]:
#Hint: here's a useful programming pattern to use.
try:
    #do something
except Exception as e:
    #handle your exception e

In [ ]:
#Your code here